apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storage-class
  # minikube supports PersistentVolumes of type hostPath out of the box.
  # https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
  hostPath:
    path: /data/kubernetes-training
  # nodeAffinity is required.
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - minikube